### DISCUSSION TITLE
openwrt+pve踩坑分享

### DISCUSSION THREAD

**Discussion by LetMeDecay** [kkkgo/PaoPaoGateWay#65] [配置分享]
1. 虚拟机CPU核心类别需要使用x86-64-v3以上，否则clash核心会不兼容，然后就会尝试一个127.0.0.1的代理地址。我这里是直接切成了host
2. clash-meta最新版v1.18.1 release文件有bug，换成wiki地址下载alpha版就可以了 https://wiki.metacubex.one/startup/
3. 无公网搭建paopaodns使用默认配置运行test.sh CN和NOCN都会报错，修改docker compose文件网络为host可以解决，但是需要注意paopaodns用到的端口是否和主机冲突，配置文件在下面
4. 手机无法关闭ipv6，我的小米会出现不走网关的情况，解析优先使用v6的dns，修改openwrt设置，让其下发无效的dns可以解决，比如`::1`。我这里不希望其他设备走网关，所以没有下发v6的paopaodns，不然也可以解决问题
5. suburl模式下，fast_node=yes会忽略订阅的规则，强制global模式，如果想用sub转换器的广告过滤规则之类的功能，需要改成check或者no，缺点是不会自动切节点

```
mode=suburl

# Set fakeip's CIDR here
# default: fake_cidr=7.0.0.0/8
fake_cidr=7.0.0.0/8

# Set your trusted DNS here
# default: dns_ip=1.0.0.1
dns_ip=192.168.31.52 # paopaodns主机ip
# default: dns_port=53
# If used with PaoPaoDNS, you can set the 5304 port
dns_port=5304

# Clash's web dashboard
clash_web_port="80"
clash_web_password="password"

# default：openport=no
# socks+http mixed 1080
openport=yes

# default: udp_enable=no
udp_enable=no

# default:30
sleeptime=30

# suburl mode settting
suburl="https://sub.xeton.dev/sub?target=clash&new_name=true&url="
subtime=6h

# fast_node=check/yes/no
fast_node=check
test_node_url="https://www.youtube.com/generate_204"
ext_node="Traffic|Expire| GB|Days|Date"
cpudelay="3000"

# dns burn setting
# depend on fast_node=yes & mode=suburl/yaml
dns_burn=yes
# If used with PaoPaoDNS, you can set the PaoPaoDNS:53
ex_dns="192.168.31.52:53"

# Network traffic records
net_rec=yes
max_rec=5000
```

```
version: "3"

services:
  paopaodns:
    image: sliamb/paopaodns:latest
    container_name: paopaodns
    network_mode: "host"
    restart: always
    volumes:
      - /home/paopaodns:/data
    environment:
      - TZ=Asia/Shanghai
      - UPDATE=weekly
      - DNS_SERVERNAME=PaoPaoDNS,blog.03k.org
      - DNSPORT=53
      - CNAUTO=yes
      - CNFALL=yes
      - CN_TRACKER=yes
      - USE_HOSTS=no
      - IPV6=no
      - SOCKS5=192.168.31.100:1080 #paopaogateway ip
      - SERVER_IP=192.168.31.52 #主机ip
      - CUSTOM_FORWARD=192.168.31.100:53 #paopaogateway ip
      - AUTO_FORWARD=yes
      - AUTO_FORWARD_CHECK=yes
      - USE_MARK_DATA=yes
      - ADDINFO=yes
      - HTTP_FILE=yes
```
